# Generated by Django 4.2.21 on 2025-07-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('jackets', 'Jackets'), ('knitwear', 'Knitwear'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('bags', 'Bags'), ('activewear', 'Activewear'), ('formal', 'Formal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('vintage', 'Vintage')], max_length=20),
        ),
    ]
