# Generated by Django 4.2.21 on 2025-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_category_alter_item_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
