# Generated by Django 4.2.21 on 2025-07-12 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_item_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('meetup_pending', 'Pending Meetup'), ('awaiting_response', 'Awaiting Response')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_swaps', to=settings.AUTH_USER_MODEL)),
                ('proposer_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposer_swaps', to='items.item')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL)),
                ('receiver_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_swaps', to='items.item')),
            ],
        ),
    ]
